name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
        with:
          heroku_api_key: ${{secrets.c8ad41db-af6b-4d7d-b571-a9b160ed0565}}
          heroku_app_name: "test132131234" #Must be unique in Heroku
          heroku_email: "justaqiel@gmail.com"
